//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Words
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment_t
    {
        public int Comment_Id { get; set; }
        public int Comment_TargetId { get; set; }
        public System.Guid Comment_Author { get; set; }
        public string Comment_Content { get; set; }
        public System.DateTime Comment_CreateDt { get; set; }
    }
}
